const LOGIN = 'login';
const HOME='home';
const REGISTER = 'register';
const  CATEGORIES= 'categories';
const CHANGEFAVORITES = 'favorites';
const GETFAV= 'favorites';
const GETPROFILE= 'profile';
const LOGOUT = 'logout';
const UPDADTEPROFILE = 'update-profile';
